
export type GetTokenResError = 'WRONG_GRANT_TYPE' |
	'INVALID_AUTHORIZATION_CODE' |
	'NO_SESSION_DATA' |
	'REDIS_ERR' |
	'KEY_NOT_FOUND' |
	'REDIS_FAILED_TOKEN_STORAGE';

export type GetCredentialResError = 'NO_PROOF_PROVIDED' |
	'PROOF_TYPE_NOT_SUPPORTED' |
	'WRONG_HOLDER_PUB_KEY' |
	'INVALID_PROOF_SIGNATURE' |
	'REDIS_ERR' |
	'KEY_NOT_FOUND' |
	'INCORRECT_TOKEN' |
	'INCORRECT_C_NONCE' |
	'TOKEN_EXPIRED' |
	'C_NONCE_EXPIRED' |
	'NON_EXISTENT_SESSION' |
	'NO_SELECTED_CREDENTIALS' |
	'NO_CREDENTIAL_TYPE_PROVIDED' |
	'NOT_A_SUPPORTED_CREDENTIAL_TYPE' |
	'NO_USER_SESSION' |
	'NO_SESSION_IDENTIFIER' |
	'ERROR_CREATING_CREDENTIAL_SUBJECT';
