name: Build Docker image

on:
  push:
    branches-ignore:
      - master  # Covered by docker-push.yml
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    # Permissions for GITHUB_TOKEN
    permissions:
      contents: read  # To check out repo

    steps:
    - uses: actions/checkout@v4

    - uses: docker/build-push-action@v6
      with:
        push: false
